# Generated by Django 5.2.15 on 2026-06-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0002_deposit_is_verified_deposit_payment_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='account_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
